package chap12;

public class RecordTests {

    private static void isSame(Record first, Record second) {
        if (first.equals(second))
        {
            System.out.println(first + " is the same as " + second);
        }
        else
        {
            System.out.println(first + " is NOT the same as " + second);
        }
    }

    public static void main(String[] args) {
        {
            // NameHolder is a record type defined as an inner record (see below)
            // Equals, hashCode, toString are all default generated by compiler
            var jamesBond = new NameHolder("James", "Bond");
            System.out.println(jamesBond);

            var jimBond = new NameHolder("Jim", "Bond");
            System.out.println(jimBond);

            isSame(jamesBond, jamesBond);
            isSame(jamesBond, jimBond);
        }

        System.out.println("");
        System.out.println("=================");
        System.out.println("");

        {
            // NameHolder is a record type with extras
            // Equals, hashCode, toString are all overridden methods defined in the record itself.
            var jamesBond = new NameHolderWithExtras("James", "Bond");
            var seanConnery = new NameHolderWithExtras("Sean", "Connery");
            System.out.println(jamesBond);

            var jimBond = new NameHolderWithExtras("Jim", "Bond");
            System.out.println(jimBond);

            isSame(jamesBond, jamesBond);
            isSame(jamesBond, jimBond);
            isSame(jamesBond, seanConnery);

            var mysteryBond = new NameHolderWithExtras();
            isSame(jamesBond, mysteryBond);

            System.out.println("Instance count: " + NameHolderWithExtras.getInstanceCount());
        }
    }

    /**
     * Record defined as inner record.
     */
    private record NameHolder(String firstName, String lastName) {
    }
}
